import { HOST_ACTION_KIND, type HostActionKind, isHostActionKind } from "./host-action-contract.js";
import {
  ACTION_OPERATION_DOMAIN_TERMINAL_STATES,
  ACTION_OPERATION_STATE,
  type ActionOperationDomainTerminalState,
  type ActionOperationState,
} from "./protocol-contract.js";
import {
  PUBLIC_OPERATION_FIXED_PHASE,
  PUBLIC_OPERATION_PHASE_PREFIX,
  PUBLIC_OPERATION_PREFIXED_PHASE,
  PUBLIC_OPERATION_PROGRESS_STATUS,
  type PUBLIC_OPERATION_REVISION_PHASE,
  type PublicOperationPhaseV1,
  type PublicOperationProgressStatusV1,
  type PublicOperationStateDependentStatusPhaseV1,
  isPublicOperationParticipantTargetPhase,
  isPublicOperationPhase,
  isPublicOperationStateDependentStatusPhase,
  publicOperationTargetOutcomes,
} from "./public-operation-contract.js";

export const publicOperationRevisionPhase = (
  state: (typeof PUBLIC_OPERATION_REVISION_PHASE)[keyof typeof PUBLIC_OPERATION_REVISION_PHASE],
): (typeof PUBLIC_OPERATION_PREFIXED_PHASE.REVISION)[keyof typeof PUBLIC_OPERATION_PREFIXED_PHASE.REVISION] =>
  `${PUBLIC_OPERATION_PHASE_PREFIX.REVISION}:${state}`;

const REVISION_ACTIONS = Object.freeze([
  HOST_ACTION_KIND.CONVERSATION_ADD_PARTICIPANT,
  HOST_ACTION_KIND.CONVERSATION_REMOVE_PARTICIPANT,
  HOST_ACTION_KIND.CONVERSATION_UPDATE_PARTICIPANT,
  HOST_ACTION_KIND.CONVERSATION_UPDATE_SETTINGS,
  HOST_ACTION_KIND.CONVERSATION_CONTINUE_MESSAGE,
  HOST_ACTION_KIND.CONVERSATION_ABANDON_REVISION_OPERATION,
  HOST_ACTION_KIND.CONVERSATION_RETRY_REVISION_OPERATION,
  HOST_ACTION_KIND.CONVERSATION_RECONCILE_REVISION_OPERATION,
] as const);

const RECEIPT_ACTIONS = Object.freeze([
  HOST_ACTION_KIND.CONVERSATION_SELECT_LINEAGE_HEAD,
  HOST_ACTION_KIND.CONVERSATION_ASSOCIATE_LINEAGES,
  HOST_ACTION_KIND.CONVERSATION_PUBLISH_SUSPECTED_LITERAL,
  HOST_ACTION_KIND.CONVERSATION_STOP_OPERATION,
  HOST_ACTION_KIND.CONTEXT_COMPACT,
] as const);

const AUTHORITY_ACTIONS = Object.freeze([
  HOST_ACTION_KIND.GRANT_CREATE,
  HOST_ACTION_KIND.GRANT_RENEW,
  HOST_ACTION_KIND.GRANT_REVOKE,
  HOST_ACTION_KIND.POLICY_UPDATE_AUTHORITY,
  HOST_ACTION_KIND.SECRET_REVOKE,
  HOST_ACTION_KIND.REGISTRY_TRUST_KEY,
] as const);

const CAPABILITY_NON_TARGET_PHASES = Object.freeze([
  PUBLIC_OPERATION_FIXED_PHASE.OPERATION_SUCCEEDED,
  PUBLIC_OPERATION_FIXED_PHASE.OPERATION_FAILED,
  PUBLIC_OPERATION_FIXED_PHASE.OPERATION_NEEDS_RECOVERY,
] as const);

type FixedStatusPhase = Exclude<PublicOperationPhaseV1, PublicOperationStateDependentStatusPhaseV1>;

const FIXED_STATUS = Object.freeze({
  [PUBLIC_OPERATION_FIXED_PHASE.DISPATCH]: PUBLIC_OPERATION_PROGRESS_STATUS.RUNNING,
  [PUBLIC_OPERATION_FIXED_PHASE.OPERATION_STARTED]: PUBLIC_OPERATION_PROGRESS_STATUS.RUNNING,
  [PUBLIC_OPERATION_FIXED_PHASE.TARGET_APPLIED]: PUBLIC_OPERATION_PROGRESS_STATUS.SUCCEEDED,
  [PUBLIC_OPERATION_FIXED_PHASE.TARGET_OMITTED]: PUBLIC_OPERATION_PROGRESS_STATUS.REVERSED,
  [PUBLIC_OPERATION_FIXED_PHASE.TARGET_REVERSED]: PUBLIC_OPERATION_PROGRESS_STATUS.REVERSED,
  [PUBLIC_OPERATION_FIXED_PHASE.TARGET_DEGRADED]: PUBLIC_OPERATION_PROGRESS_STATUS.FAILED,
  [PUBLIC_OPERATION_FIXED_PHASE.TARGET_FAILED]: PUBLIC_OPERATION_PROGRESS_STATUS.FAILED,
  [PUBLIC_OPERATION_FIXED_PHASE.TARGET_BLOCKED]: PUBLIC_OPERATION_PROGRESS_STATUS.FAILED,
  [PUBLIC_OPERATION_FIXED_PHASE.TARGET_NEEDS_RECOVERY]: PUBLIC_OPERATION_PROGRESS_STATUS.FAILED,
  [PUBLIC_OPERATION_FIXED_PHASE.OPERATION_SUCCEEDED]: PUBLIC_OPERATION_PROGRESS_STATUS.SUCCEEDED,
  [PUBLIC_OPERATION_FIXED_PHASE.OPERATION_FAILED]: PUBLIC_OPERATION_PROGRESS_STATUS.FAILED,
  [PUBLIC_OPERATION_FIXED_PHASE.OPERATION_NEEDS_RECOVERY]: PUBLIC_OPERATION_PROGRESS_STATUS.FAILED,
  [PUBLIC_OPERATION_PREFIXED_PHASE.PARTICIPANT_START.PREPARED]:
    PUBLIC_OPERATION_PROGRESS_STATUS.PENDING,
  [PUBLIC_OPERATION_PREFIXED_PHASE.PARTICIPANT_START.EFFECT_IN_PROGRESS]:
    PUBLIC_OPERATION_PROGRESS_STATUS.RUNNING,
  [PUBLIC_OPERATION_PREFIXED_PHASE.PARTICIPANT_START.OBSERVED]:
    PUBLIC_OPERATION_PROGRESS_STATUS.RUNNING,
  [PUBLIC_OPERATION_PREFIXED_PHASE.PARTICIPANT_START.CANCEL_IN_PROGRESS]:
    PUBLIC_OPERATION_PROGRESS_STATUS.RUNNING,
  [PUBLIC_OPERATION_PREFIXED_PHASE.PARTICIPANT_START.ACCEPTED]:
    PUBLIC_OPERATION_PROGRESS_STATUS.SUCCEEDED,
  [PUBLIC_OPERATION_PREFIXED_PHASE.PARTICIPANT_START.FAILED]:
    PUBLIC_OPERATION_PROGRESS_STATUS.FAILED,
  [PUBLIC_OPERATION_PREFIXED_PHASE.PARTICIPANT_START.CANCELED]:
    PUBLIC_OPERATION_PROGRESS_STATUS.REVERSED,
  [PUBLIC_OPERATION_PREFIXED_PHASE.PARTICIPANT_START.UNCERTAIN]:
    PUBLIC_OPERATION_PROGRESS_STATUS.FAILED,
  [PUBLIC_OPERATION_PREFIXED_PHASE.AUTHORITY_CHANGE.PREPARED]:
    PUBLIC_OPERATION_PROGRESS_STATUS.PENDING,
  [PUBLIC_OPERATION_PREFIXED_PHASE.AUTHORITY_CHANGE.EFFECT_IN_PROGRESS]:
    PUBLIC_OPERATION_PROGRESS_STATUS.RUNNING,
  [PUBLIC_OPERATION_PREFIXED_PHASE.AUTHORITY_CHANGE.OBSERVED]:
    PUBLIC_OPERATION_PROGRESS_STATUS.SUCCEEDED,
  [PUBLIC_OPERATION_PREFIXED_PHASE.AUTHORITY_CHANGE.EPOCH_COMMITTED]:
    PUBLIC_OPERATION_PROGRESS_STATUS.SUCCEEDED,
  [PUBLIC_OPERATION_PREFIXED_PHASE.AUTHORITY_CHANGE.FAILED]:
    PUBLIC_OPERATION_PROGRESS_STATUS.FAILED,
  [PUBLIC_OPERATION_PREFIXED_PHASE.AUTHORITY_CHANGE.NEEDS_RECOVERY]:
    PUBLIC_OPERATION_PROGRESS_STATUS.FAILED,
  [PUBLIC_OPERATION_PREFIXED_PHASE.AUTHORITY_REPAIR.PREPARED]:
    PUBLIC_OPERATION_PROGRESS_STATUS.PENDING,
  [PUBLIC_OPERATION_PREFIXED_PHASE.AUTHORITY_REPAIR.PREIMAGE_FSYNCED]:
    PUBLIC_OPERATION_PROGRESS_STATUS.SUCCEEDED,
  [PUBLIC_OPERATION_PREFIXED_PHASE.AUTHORITY_REPAIR.RESTORE_IN_PROGRESS]:
    PUBLIC_OPERATION_PROGRESS_STATUS.RUNNING,
  [PUBLIC_OPERATION_PREFIXED_PHASE.AUTHORITY_REPAIR.RESTORED]:
    PUBLIC_OPERATION_PROGRESS_STATUS.SUCCEEDED,
  [PUBLIC_OPERATION_PREFIXED_PHASE.AUTHORITY_REPAIR.VERIFIED]:
    PUBLIC_OPERATION_PROGRESS_STATUS.SUCCEEDED,
  [PUBLIC_OPERATION_PREFIXED_PHASE.AUTHORITY_REPAIR.FAILED]:
    PUBLIC_OPERATION_PROGRESS_STATUS.FAILED,
  [PUBLIC_OPERATION_PREFIXED_PHASE.AUTHORITY_REPAIR.NEEDS_RECOVERY]:
    PUBLIC_OPERATION_PROGRESS_STATUS.FAILED,
  [PUBLIC_OPERATION_PREFIXED_PHASE.CONVERSATION_RECEIPT.SUCCEEDED]:
    PUBLIC_OPERATION_PROGRESS_STATUS.SUCCEEDED,
  [PUBLIC_OPERATION_PREFIXED_PHASE.CONVERSATION_RECEIPT.FAILED]:
    PUBLIC_OPERATION_PROGRESS_STATUS.FAILED,
  [PUBLIC_OPERATION_PREFIXED_PHASE.CONVERSATION_RECEIPT.NEEDS_RECOVERY]:
    PUBLIC_OPERATION_PROGRESS_STATUS.FAILED,
  [PUBLIC_OPERATION_FIXED_PHASE.LINEAGE_HEAD_COMMITTED]: PUBLIC_OPERATION_PROGRESS_STATUS.SUCCEEDED,
  [PUBLIC_OPERATION_FIXED_PHASE.LINEAGE_ASSOCIATION_COMMITTED]:
    PUBLIC_OPERATION_PROGRESS_STATUS.SUCCEEDED,
  [PUBLIC_OPERATION_FIXED_PHASE.CONTEXT_COMPACTION_COMMITTED]:
    PUBLIC_OPERATION_PROGRESS_STATUS.SUCCEEDED,
  [PUBLIC_OPERATION_FIXED_PHASE.PUBLIC_LITERAL_PUBLISHED]:
    PUBLIC_OPERATION_PROGRESS_STATUS.SUCCEEDED,
  [PUBLIC_OPERATION_PREFIXED_PHASE.REVISION.PREPARING]: PUBLIC_OPERATION_PROGRESS_STATUS.RUNNING,
  [PUBLIC_OPERATION_PREFIXED_PHASE.REVISION.STARTING]: PUBLIC_OPERATION_PROGRESS_STATUS.RUNNING,
  [PUBLIC_OPERATION_PREFIXED_PHASE.REVISION.PREPARED]: PUBLIC_OPERATION_PROGRESS_STATUS.SUCCEEDED,
  [PUBLIC_OPERATION_PREFIXED_PHASE.REVISION.PUBLISHED]: PUBLIC_OPERATION_PROGRESS_STATUS.SUCCEEDED,
} satisfies Readonly<Record<FixedStatusPhase, PublicOperationProgressStatusV1>>);

const TERMINAL_PHASES = Object.freeze({
  [ACTION_OPERATION_STATE.SUCCEEDED]: Object.freeze([
    PUBLIC_OPERATION_FIXED_PHASE.OPERATION_SUCCEEDED,
    PUBLIC_OPERATION_FIXED_PHASE.LINEAGE_HEAD_COMMITTED,
    PUBLIC_OPERATION_FIXED_PHASE.LINEAGE_ASSOCIATION_COMMITTED,
    PUBLIC_OPERATION_FIXED_PHASE.CONTEXT_COMPACTION_COMMITTED,
    PUBLIC_OPERATION_FIXED_PHASE.PUBLIC_LITERAL_PUBLISHED,
    PUBLIC_OPERATION_PREFIXED_PHASE.CONVERSATION_RECEIPT.SUCCEEDED,
    PUBLIC_OPERATION_PREFIXED_PHASE.AUTHORITY_CHANGE.EPOCH_COMMITTED,
    PUBLIC_OPERATION_PREFIXED_PHASE.AUTHORITY_REPAIR.VERIFIED,
  ] as const),
  [ACTION_OPERATION_STATE.FAILED]: Object.freeze([
    PUBLIC_OPERATION_FIXED_PHASE.OPERATION_FAILED,
    PUBLIC_OPERATION_PREFIXED_PHASE.CONVERSATION_RECEIPT.FAILED,
    PUBLIC_OPERATION_PREFIXED_PHASE.AUTHORITY_CHANGE.FAILED,
    PUBLIC_OPERATION_PREFIXED_PHASE.AUTHORITY_REPAIR.FAILED,
  ] as const),
  [ACTION_OPERATION_STATE.NEEDS_RECOVERY]: Object.freeze([
    PUBLIC_OPERATION_FIXED_PHASE.OPERATION_NEEDS_RECOVERY,
    PUBLIC_OPERATION_PREFIXED_PHASE.CONVERSATION_RECEIPT.NEEDS_RECOVERY,
    PUBLIC_OPERATION_PREFIXED_PHASE.AUTHORITY_CHANGE.NEEDS_RECOVERY,
    PUBLIC_OPERATION_PREFIXED_PHASE.AUTHORITY_REPAIR.NEEDS_RECOVERY,
  ] as const),
} satisfies Readonly<
  Record<ActionOperationDomainTerminalState, readonly PublicOperationPhaseV1[]>
>);

const includes = <Value extends string>(values: readonly Value[], value: string): boolean =>
  values.some((candidate) => candidate === value);

export function expectedOperationStatus(
  phase: PublicOperationPhaseV1,
  state: ActionOperationState,
): PublicOperationProgressStatusV1 {
  if (!isPublicOperationStateDependentStatusPhase(phase)) return FIXED_STATUS[phase];
  if (state === ACTION_OPERATION_STATE.SUCCEEDED) return PUBLIC_OPERATION_PROGRESS_STATUS.SUCCEEDED;
  if (state === ACTION_OPERATION_STATE.FAILED || state === ACTION_OPERATION_STATE.NEEDS_RECOVERY)
    return PUBLIC_OPERATION_PROGRESS_STATUS.FAILED;
  throw new Error("operation phase has no exact progress-status mapping");
}

export function terminalStateForPhase(phase: unknown): ActionOperationDomainTerminalState | null {
  if (!isPublicOperationPhase(phase)) return null;
  for (const state of ACTION_OPERATION_DOMAIN_TERMINAL_STATES) {
    if ((TERMINAL_PHASES[state] as readonly PublicOperationPhaseV1[]).includes(phase)) return state;
  }
  return null;
}

function isRevisionTerminalPhaseStateValid(input: {
  actionType: unknown;
  phase: PublicOperationStateDependentStatusPhaseV1;
  state: ActionOperationState;
}): boolean {
  switch (input.phase) {
    case PUBLIC_OPERATION_PREFIXED_PHASE.REVISION.STARTED:
      return input.state === ACTION_OPERATION_STATE.SUCCEEDED;
    case PUBLIC_OPERATION_PREFIXED_PHASE.REVISION.START_FAILED:
      return input.actionType === HOST_ACTION_KIND.CONVERSATION_RECONCILE_REVISION_OPERATION
        ? input.state === ACTION_OPERATION_STATE.SUCCEEDED
        : input.state === ACTION_OPERATION_STATE.FAILED;
    case PUBLIC_OPERATION_PREFIXED_PHASE.REVISION.NEEDS_RECOVERY:
      return input.actionType === HOST_ACTION_KIND.CONVERSATION_RECONCILE_REVISION_OPERATION
        ? input.state === ACTION_OPERATION_STATE.FAILED
        : input.state === ACTION_OPERATION_STATE.NEEDS_RECOVERY;
    case PUBLIC_OPERATION_PREFIXED_PHASE.REVISION.ABANDONED:
      return input.actionType === HOST_ACTION_KIND.CONVERSATION_ABANDON_REVISION_OPERATION ||
        input.actionType === HOST_ACTION_KIND.CONVERSATION_RECONCILE_REVISION_OPERATION
        ? input.state === ACTION_OPERATION_STATE.SUCCEEDED
        : input.state === ACTION_OPERATION_STATE.FAILED;
  }
}

export function isPublicOperationPhaseStateValid(input: {
  actionType: unknown;
  phase: PublicOperationPhaseV1;
  phaseSequence: number;
  state: ActionOperationState;
}): boolean {
  if (
    !isPublicOperationPhaseOwned({
      actionType: input.actionType,
      phase: input.phase,
      phaseSequence: input.phaseSequence,
    })
  )
    return false;
  if (input.phaseSequence === 0) return input.state === ACTION_OPERATION_STATE.COMMITTING;
  const exactTerminal = terminalStateForPhase(input.phase);
  if (exactTerminal !== null) return input.state === exactTerminal;
  if (isPublicOperationStateDependentStatusPhase(input.phase))
    return isRevisionTerminalPhaseStateValid({
      actionType: input.actionType,
      phase: input.phase,
      state: input.state,
    });
  if (publicOperationTargetOutcomes(input.phase) !== null)
    return ACTION_OPERATION_DOMAIN_TERMINAL_STATES.some((candidate) => candidate === input.state);
  if (
    input.actionType === HOST_ACTION_KIND.CONVERSATION_RECONCILE_REVISION_OPERATION &&
    phaseFamily(input.phase, PUBLIC_OPERATION_PHASE_PREFIX.REVISION) &&
    input.state === ACTION_OPERATION_STATE.SUCCEEDED
  )
    return true;
  return input.state === ACTION_OPERATION_STATE.COMMITTING;
}

export function isPublicOperationPhaseOwned(input: {
  actionType: unknown;
  phase: PublicOperationPhaseV1;
  phaseSequence: number;
}): boolean {
  if (!isHostActionKind(input.actionType) || !Number.isSafeInteger(input.phaseSequence))
    return false;
  const capability = input.actionType.startsWith("capability.");
  if (input.phaseSequence === 0)
    return (
      input.phase ===
      (capability
        ? PUBLIC_OPERATION_FIXED_PHASE.OPERATION_STARTED
        : PUBLIC_OPERATION_FIXED_PHASE.DISPATCH)
    );
  if (input.phaseSequence < 1) return false;
  if (capability)
    return (
      (publicOperationTargetOutcomes(input.phase) !== null &&
        !isPublicOperationParticipantTargetPhase(input.phase)) ||
      includes(CAPABILITY_NON_TARGET_PHASES, input.phase)
    );
  if (includes(REVISION_ACTIONS, input.actionType))
    return (
      phaseFamily(input.phase, PUBLIC_OPERATION_PHASE_PREFIX.REVISION) ||
      phaseFamily(input.phase, PUBLIC_OPERATION_PHASE_PREFIX.PARTICIPANT_START)
    );
  if (includes(RECEIPT_ACTIONS, input.actionType))
    return receiptPhaseMatches(input.actionType, input.phase);
  if (includes(AUTHORITY_ACTIONS, input.actionType))
    return phaseFamily(input.phase, PUBLIC_OPERATION_PHASE_PREFIX.AUTHORITY_CHANGE);
  return (
    input.actionType === HOST_ACTION_KIND.AUTHORITY_REPAIR &&
    phaseFamily(input.phase, PUBLIC_OPERATION_PHASE_PREFIX.AUTHORITY_REPAIR)
  );
}

const phaseFamily = (phase: PublicOperationPhaseV1, prefix: string): boolean =>
  phase.startsWith(`${prefix}:`);

function receiptPhaseMatches(action: HostActionKind, phase: PublicOperationPhaseV1): boolean {
  if (
    phase === PUBLIC_OPERATION_PREFIXED_PHASE.CONVERSATION_RECEIPT.FAILED ||
    phase === PUBLIC_OPERATION_PREFIXED_PHASE.CONVERSATION_RECEIPT.NEEDS_RECOVERY
  )
    return true;
  const success = {
    [HOST_ACTION_KIND.CONVERSATION_SELECT_LINEAGE_HEAD]:
      PUBLIC_OPERATION_FIXED_PHASE.LINEAGE_HEAD_COMMITTED,
    [HOST_ACTION_KIND.CONVERSATION_ASSOCIATE_LINEAGES]:
      PUBLIC_OPERATION_FIXED_PHASE.LINEAGE_ASSOCIATION_COMMITTED,
    [HOST_ACTION_KIND.CONVERSATION_PUBLISH_SUSPECTED_LITERAL]:
      PUBLIC_OPERATION_FIXED_PHASE.PUBLIC_LITERAL_PUBLISHED,
    [HOST_ACTION_KIND.CONVERSATION_STOP_OPERATION]:
      PUBLIC_OPERATION_PREFIXED_PHASE.CONVERSATION_RECEIPT.SUCCEEDED,
    [HOST_ACTION_KIND.CONTEXT_COMPACT]: PUBLIC_OPERATION_FIXED_PHASE.CONTEXT_COMPACTION_COMMITTED,
  } satisfies Partial<Readonly<Record<HostActionKind, PublicOperationPhaseV1>>>;
  return phase === success[action as keyof typeof success];
}
