export function skillTemplate(name: string, opts?: { scope?: string }): string {
  const scopeLine = opts?.scope ? `scope: ${opts.scope}` : "scope: common";
  return [
    "---",
    `name: ${name}`,
    scopeLine,
    "description: One-line summary of what this skill does and when to apply it.",
    "status: draft",
    "capabilities:",
    "  - capability-keyword",
    "triggers:",
    "  - trigger-keyword",
    "requires:",
    "  filesystem: read",
    "  network: false",
    "  shell: false",
    "---",
    "",
    `# ${name}`,
    "",
    "## When to use",
    "Describe the task shape that should invoke this skill.",
    "",
    "## Steps",
    "1. First concrete step.",
    "2. Next step.",
    "",
    "## Verification",
    "How to prove the skill was applied correctly (command output, file check, test).",
    "",
  ].join("\n");
}

export function draftSkillTemplate(name: string, opts?: { scope?: string }): string {
  const scopeLine = opts?.scope ? `scope: ${opts.scope}` : "scope: common";
  return [
    "---",
    `name: ${name}`,
    scopeLine,
    "description: One-line summary of the reusable procedure this skill captures.",
    "status: draft",
    "triggers:",
    "  - trigger-keyword",
    "---",
    "",
    `# ${name}`,
    "",
    "## Why this exists",
    "What recurring task, mistake, or workaround prompted capturing this? (1-2 lines)",
    "",
    "## Evidence",
    "- Concrete proof this approach worked (command output, file path, test result).",
    "",
    "## When to use",
    "The task shape that should invoke this skill.",
    "",
    "## Steps",
    "1. First concrete step.",
    "2. Next step.",
    "",
    "## Verification",
    "How to prove the skill was applied correctly.",
    "",
    "> DRAFT — captured from a real task. Review and refine before relying on it.",
    "",
  ].join("\n");
}
