import {
  ACTION_OPERATION_STATE,
  type ActionOperationDispatchReplayState,
} from "../../actions/protocol-contract.js";
import {
  PUBLIC_RECOVERY_ACTION,
  type RecoveryAction,
} from "../../actions/public-error-contract.js";
import {
  PUBLIC_ERROR_PRE_EFFECT_FRONTIER,
  PUBLIC_ERROR_PRE_EFFECT_REASON,
} from "../../actions/public-error-details-contract.js";
import {
  PUBLIC_TARGET_RESULT_HEALTH,
  PUBLIC_TARGET_RESULT_HEALTHS,
  PUBLIC_TARGET_RESULT_OUTCOME,
} from "../../actions/public-operation-contract.js";
import { CAPABILITY_RUNTIME_ERROR_CODE } from "../../core/capability-contract.js";

type ValueOf<Contract> = Contract[keyof Contract];

const frozenValues = <const Values extends readonly string[]>(
  ...values: Values
): Readonly<Values> => Object.freeze(values);

const memberOf = <Value extends string>(values: readonly Value[], value: unknown): value is Value =>
  typeof value === "string" && values.some((candidate) => candidate === value);

export const CAPABILITY_PRE_EFFECT_REFUSAL_REASON = PUBLIC_ERROR_PRE_EFFECT_REASON;
export type CapabilityPreEffectRefusalReasonV1 = ValueOf<
  typeof CAPABILITY_PRE_EFFECT_REFUSAL_REASON
>;
export const CAPABILITY_PRE_EFFECT_REFUSAL_REASONS = Object.freeze(
  Object.values(CAPABILITY_PRE_EFFECT_REFUSAL_REASON),
);

export const CAPABILITY_PRE_EFFECT_FRONTIER = PUBLIC_ERROR_PRE_EFFECT_FRONTIER;
export type CapabilityPreEffectFrontierV1 = ValueOf<typeof CAPABILITY_PRE_EFFECT_FRONTIER>;
export const CAPABILITY_PRE_EFFECT_FRONTIERS = Object.freeze(
  Object.values(CAPABILITY_PRE_EFFECT_FRONTIER),
);

export const CAPABILITY_PRE_EFFECT_OBSERVED_STATE = Object.freeze({
  ABSENT: "absent",
  CHANGED: "changed",
  EXPIRED: "expired",
  REVOKED: "revoked",
  EPOCH_DRIFT: "epoch-drift",
  SCOPE_MISMATCH: "scope-mismatch",
  UNAVAILABLE: "unavailable",
} as const);
export type CapabilityPreEffectObservedStateV1 = ValueOf<
  typeof CAPABILITY_PRE_EFFECT_OBSERVED_STATE
>;
export const CAPABILITY_PRE_EFFECT_OBSERVED_STATES = Object.freeze(
  Object.values(CAPABILITY_PRE_EFFECT_OBSERVED_STATE),
);
export const CAPABILITY_PRE_EFFECT_OBSERVED_STATES_BY_REASON = Object.freeze({
  [CAPABILITY_PRE_EFFECT_REFUSAL_REASON.SCOPE_BASE_STALE]: frozenValues(
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.ABSENT,
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.CHANGED,
  ),
  [CAPABILITY_PRE_EFFECT_REFUSAL_REASON.AUTHORITY_HEAD_STALE]: frozenValues(
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.CHANGED,
  ),
  [CAPABILITY_PRE_EFFECT_REFUSAL_REASON.POLICY_STALE]: frozenValues(
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.ABSENT,
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.CHANGED,
  ),
  [CAPABILITY_PRE_EFFECT_REFUSAL_REASON.GRANT_STALE]: frozenValues(
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.ABSENT,
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.REVOKED,
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.EXPIRED,
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.CHANGED,
  ),
  [CAPABILITY_PRE_EFFECT_REFUSAL_REASON.PERMISSION_STALE]: frozenValues(
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.ABSENT,
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.SCOPE_MISMATCH,
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.CHANGED,
  ),
  [CAPABILITY_PRE_EFFECT_REFUSAL_REASON.USER_PREREQUISITE_STALE]: frozenValues(
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.ABSENT,
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.SCOPE_MISMATCH,
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.EPOCH_DRIFT,
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.EXPIRED,
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.CHANGED,
  ),
  [CAPABILITY_PRE_EFFECT_REFUSAL_REASON.SOURCE_AUTHORITY_STALE]: frozenValues(
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.ABSENT,
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.SCOPE_MISMATCH,
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.EPOCH_DRIFT,
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.REVOKED,
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.EXPIRED,
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.UNAVAILABLE,
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.CHANGED,
  ),
  [CAPABILITY_PRE_EFFECT_REFUSAL_REASON.PRIVATE_INPUT_STALE]: frozenValues(
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.ABSENT,
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.SCOPE_MISMATCH,
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.EPOCH_DRIFT,
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.REVOKED,
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.EXPIRED,
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.CHANGED,
  ),
  [CAPABILITY_PRE_EFFECT_REFUSAL_REASON.ENFORCEMENT_STALE]: frozenValues(
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.ABSENT,
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.SCOPE_MISMATCH,
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.UNAVAILABLE,
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.CHANGED,
  ),
  [CAPABILITY_PRE_EFFECT_REFUSAL_REASON.OWNED_PREIMAGE_STALE]: frozenValues(
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.ABSENT,
    CAPABILITY_PRE_EFFECT_OBSERVED_STATE.CHANGED,
  ),
} satisfies Readonly<
  Record<CapabilityPreEffectRefusalReasonV1, readonly CapabilityPreEffectObservedStateV1[]>
>);
export const CAPABILITY_PRE_EFFECT_AUTHORITY_REFUSAL_REASONS = frozenValues(
  CAPABILITY_PRE_EFFECT_REFUSAL_REASON.AUTHORITY_HEAD_STALE,
  CAPABILITY_PRE_EFFECT_REFUSAL_REASON.POLICY_STALE,
  CAPABILITY_PRE_EFFECT_REFUSAL_REASON.GRANT_STALE,
  CAPABILITY_PRE_EFFECT_REFUSAL_REASON.PERMISSION_STALE,
  CAPABILITY_PRE_EFFECT_REFUSAL_REASON.SOURCE_AUTHORITY_STALE,
);

export const isCapabilityPreEffectRefusalReason = (
  value: unknown,
): value is CapabilityPreEffectRefusalReasonV1 =>
  memberOf(CAPABILITY_PRE_EFFECT_REFUSAL_REASONS, value);
export const isCapabilityPreEffectFrontier = (
  value: unknown,
): value is CapabilityPreEffectFrontierV1 => memberOf(CAPABILITY_PRE_EFFECT_FRONTIERS, value);
export const isCapabilityPreEffectObservedState = (
  value: unknown,
): value is CapabilityPreEffectObservedStateV1 =>
  memberOf(CAPABILITY_PRE_EFFECT_OBSERVED_STATES, value);

export const CAPABILITY_ADAPTER_RECEIPT_STATE = Object.freeze({
  PREPARED: "prepared",
  EFFECT_IN_PROGRESS: "effect_in_progress",
  APPLIED: "applied",
  REVERSE_IN_PROGRESS: "reverse_in_progress",
  REVERSED: "reversed",
  FAILED: "failed",
  UNCERTAIN: "uncertain",
} as const);
export type CapabilityAdapterReceiptStateV1 = ValueOf<typeof CAPABILITY_ADAPTER_RECEIPT_STATE>;
export const CAPABILITY_ADAPTER_RECEIPT_STATES = Object.freeze(
  Object.values(CAPABILITY_ADAPTER_RECEIPT_STATE),
);
export const CAPABILITY_ADAPTER_RECEIPT_UNOBSERVED_STATES = frozenValues(
  CAPABILITY_ADAPTER_RECEIPT_STATE.PREPARED,
  CAPABILITY_ADAPTER_RECEIPT_STATE.EFFECT_IN_PROGRESS,
);
export const CAPABILITY_ADAPTER_RECEIPT_ACTIVE_STATES = frozenValues(
  ...CAPABILITY_ADAPTER_RECEIPT_UNOBSERVED_STATES,
  CAPABILITY_ADAPTER_RECEIPT_STATE.REVERSE_IN_PROGRESS,
  CAPABILITY_ADAPTER_RECEIPT_STATE.UNCERTAIN,
);
export type CapabilityAdapterReceiptActiveStateV1 =
  (typeof CAPABILITY_ADAPTER_RECEIPT_ACTIVE_STATES)[number];
export const CAPABILITY_ADAPTER_RECEIPT_EFFECT_UNRESOLVED_STATES = frozenValues(
  CAPABILITY_ADAPTER_RECEIPT_STATE.EFFECT_IN_PROGRESS,
  CAPABILITY_ADAPTER_RECEIPT_STATE.REVERSE_IN_PROGRESS,
  CAPABILITY_ADAPTER_RECEIPT_STATE.UNCERTAIN,
);
export type CapabilityAdapterReceiptReconciliationStateV1 =
  (typeof CAPABILITY_ADAPTER_RECEIPT_EFFECT_UNRESOLVED_STATES)[number];
export const CAPABILITY_ADAPTER_RECEIPT_OBSERVED_STATES = frozenValues(
  CAPABILITY_ADAPTER_RECEIPT_STATE.APPLIED,
  CAPABILITY_ADAPTER_RECEIPT_STATE.REVERSE_IN_PROGRESS,
  CAPABILITY_ADAPTER_RECEIPT_STATE.REVERSED,
  CAPABILITY_ADAPTER_RECEIPT_STATE.FAILED,
  CAPABILITY_ADAPTER_RECEIPT_STATE.UNCERTAIN,
);
export const CAPABILITY_ADAPTER_RECEIPT_EVIDENCE_STATES = frozenValues(
  CAPABILITY_ADAPTER_RECEIPT_STATE.APPLIED,
  CAPABILITY_ADAPTER_RECEIPT_STATE.FAILED,
  CAPABILITY_ADAPTER_RECEIPT_STATE.UNCERTAIN,
  CAPABILITY_ADAPTER_RECEIPT_STATE.REVERSED,
);
export type CapabilityAdapterReceiptEvidenceStateV1 =
  (typeof CAPABILITY_ADAPTER_RECEIPT_EVIDENCE_STATES)[number];
export const CAPABILITY_ADAPTER_RECEIPT_SUCCESS_STATES = frozenValues(
  CAPABILITY_ADAPTER_RECEIPT_STATE.APPLIED,
  CAPABILITY_ADAPTER_RECEIPT_STATE.REVERSED,
);
export const CAPABILITY_ADAPTER_RECEIPT_PUBLICATION_TERMINAL_STATES = frozenValues(
  CAPABILITY_ADAPTER_RECEIPT_STATE.APPLIED,
  CAPABILITY_ADAPTER_RECEIPT_STATE.FAILED,
  CAPABILITY_ADAPTER_RECEIPT_STATE.REVERSED,
);
export const CAPABILITY_ADAPTER_RECEIPT_COMPENSATION_STATES = frozenValues(
  CAPABILITY_ADAPTER_RECEIPT_STATE.REVERSE_IN_PROGRESS,
  CAPABILITY_ADAPTER_RECEIPT_STATE.REVERSED,
);
export const CAPABILITY_ADAPTER_RECEIPT_POSTIMAGE_ABSENT_STATES = frozenValues(
  ...CAPABILITY_ADAPTER_RECEIPT_UNOBSERVED_STATES,
  CAPABILITY_ADAPTER_RECEIPT_STATE.FAILED,
);
export const CAPABILITY_ADAPTER_RECEIPT_ERROR_STATES = frozenValues(
  CAPABILITY_ADAPTER_RECEIPT_STATE.FAILED,
  CAPABILITY_ADAPTER_RECEIPT_STATE.UNCERTAIN,
);

/** Built-in error codes recorded by adapter receipts; adapters may retain bounded private codes. */
export const CAPABILITY_ADAPTER_RECEIPT_ERROR_CODE = Object.freeze({
  APPLY_FAILED: CAPABILITY_RUNTIME_ERROR_CODE.APPLY_FAILED,
  EFFECT_NOT_APPLIED: "effect-not-applied",
  THIRD_STATE: "third-state",
  ROLLBACK_FAILED: CAPABILITY_RUNTIME_ERROR_CODE.ROLLBACK_FAILED,
} as const);

export type CapabilityAdapterReceiptErrorCodeV1 = ValueOf<
  typeof CAPABILITY_ADAPTER_RECEIPT_ERROR_CODE
>;

export const CAPABILITY_ADAPTER_RECEIPT_NEXT_STATES = Object.freeze({
  [CAPABILITY_ADAPTER_RECEIPT_STATE.PREPARED]: frozenValues(
    CAPABILITY_ADAPTER_RECEIPT_STATE.EFFECT_IN_PROGRESS,
  ),
  [CAPABILITY_ADAPTER_RECEIPT_STATE.EFFECT_IN_PROGRESS]: frozenValues(
    CAPABILITY_ADAPTER_RECEIPT_STATE.APPLIED,
    CAPABILITY_ADAPTER_RECEIPT_STATE.FAILED,
    CAPABILITY_ADAPTER_RECEIPT_STATE.UNCERTAIN,
  ),
  [CAPABILITY_ADAPTER_RECEIPT_STATE.APPLIED]: frozenValues(
    CAPABILITY_ADAPTER_RECEIPT_STATE.REVERSE_IN_PROGRESS,
  ),
  [CAPABILITY_ADAPTER_RECEIPT_STATE.REVERSE_IN_PROGRESS]: frozenValues(
    CAPABILITY_ADAPTER_RECEIPT_STATE.REVERSED,
    CAPABILITY_ADAPTER_RECEIPT_STATE.UNCERTAIN,
  ),
  [CAPABILITY_ADAPTER_RECEIPT_STATE.REVERSED]: frozenValues(),
  [CAPABILITY_ADAPTER_RECEIPT_STATE.FAILED]: frozenValues(),
  [CAPABILITY_ADAPTER_RECEIPT_STATE.UNCERTAIN]: frozenValues(
    CAPABILITY_ADAPTER_RECEIPT_STATE.APPLIED,
    CAPABILITY_ADAPTER_RECEIPT_STATE.FAILED,
    CAPABILITY_ADAPTER_RECEIPT_STATE.REVERSE_IN_PROGRESS,
    CAPABILITY_ADAPTER_RECEIPT_STATE.REVERSED,
  ),
} satisfies Readonly<
  Record<CapabilityAdapterReceiptStateV1, readonly CapabilityAdapterReceiptStateV1[]>
>);

export const isCapabilityAdapterReceiptState = (
  value: unknown,
): value is CapabilityAdapterReceiptStateV1 => memberOf(CAPABILITY_ADAPTER_RECEIPT_STATES, value);
export const isCapabilityAdapterReceiptStateIn = <State extends CapabilityAdapterReceiptStateV1>(
  states: readonly State[],
  value: CapabilityAdapterReceiptStateV1,
): value is State => memberOf(states, value);
export const isLegalCapabilityAdapterReceiptTransition = (
  prior: CapabilityAdapterReceiptStateV1 | undefined,
  next: CapabilityAdapterReceiptStateV1,
): boolean =>
  prior === undefined
    ? next === CAPABILITY_ADAPTER_RECEIPT_STATE.PREPARED
    : memberOf(CAPABILITY_ADAPTER_RECEIPT_NEXT_STATES[prior], next);

export const CAPABILITY_WAL_PAYLOAD_KIND = Object.freeze({
  OPERATION_TRANSITION: "operation-transition",
  ADAPTER_STEP: "adapter-step",
  HEALTH: "health",
  PRE_EFFECT_REFUSAL: "pre-effect-refusal",
  LOCK_CHECKPOINT: "lock-checkpoint",
  HEALTH_INVENTORY_PREPARED: "health-inventory-prepared",
  LOCK_COMMIT: "lock-commit",
  OUTBOX: "outbox",
} as const);
export type CapabilityWalPayloadKindV1 = ValueOf<typeof CAPABILITY_WAL_PAYLOAD_KIND>;
export const CAPABILITY_WAL_PAYLOAD_KINDS = Object.freeze(
  Object.values(CAPABILITY_WAL_PAYLOAD_KIND),
);
export const isCapabilityWalPayloadKind = (value: unknown): value is CapabilityWalPayloadKindV1 =>
  memberOf(CAPABILITY_WAL_PAYLOAD_KINDS, value);

export const CAPABILITY_HEALTH_OUTCOME = PUBLIC_TARGET_RESULT_HEALTH;
export type CapabilityHealthOutcomeV1 = ValueOf<typeof CAPABILITY_HEALTH_OUTCOME>;
export const CAPABILITY_HEALTH_OUTCOMES = PUBLIC_TARGET_RESULT_HEALTHS;
export const isCapabilityHealthOutcome = (value: unknown): value is CapabilityHealthOutcomeV1 =>
  memberOf(CAPABILITY_HEALTH_OUTCOMES, value);

/** Public operation result vocabulary emitted by the capability runtime. */
export const CAPABILITY_OPERATION_STATUS = Object.freeze({
  COMMITTING: ACTION_OPERATION_STATE.COMMITTING,
  SUCCEEDED: ACTION_OPERATION_STATE.SUCCEEDED,
  DEGRADED: PUBLIC_TARGET_RESULT_OUTCOME.DEGRADED,
  FAILED: ACTION_OPERATION_STATE.FAILED,
  NEEDS_RECOVERY: PUBLIC_TARGET_RESULT_OUTCOME.NEEDS_RECOVERY,
} as const);
export type CapabilityOperationStatusV1 = ValueOf<typeof CAPABILITY_OPERATION_STATUS>;
export const CAPABILITY_OPERATION_STATUSES = Object.freeze(
  Object.values(CAPABILITY_OPERATION_STATUS),
);
export const isCapabilityOperationStatus = (value: unknown): value is CapabilityOperationStatusV1 =>
  memberOf(CAPABILITY_OPERATION_STATUSES, value);

export const CAPABILITY_OPERATION_STATUS_BY_ACTION_STATE = Object.freeze({
  [ACTION_OPERATION_STATE.COMMITTING]: CAPABILITY_OPERATION_STATUS.COMMITTING,
  [ACTION_OPERATION_STATE.SUCCEEDED]: CAPABILITY_OPERATION_STATUS.SUCCEEDED,
  [ACTION_OPERATION_STATE.FAILED]: CAPABILITY_OPERATION_STATUS.FAILED,
  [ACTION_OPERATION_STATE.NEEDS_RECOVERY]: CAPABILITY_OPERATION_STATUS.NEEDS_RECOVERY,
} satisfies Readonly<Record<ActionOperationDispatchReplayState, CapabilityOperationStatusV1>>);

export const CAPABILITY_OPERATION_RECOVERY_ACTION = Object.freeze({
  RETRY: PUBLIC_RECOVERY_ACTION.RETRY,
  ROLLBACK: PUBLIC_RECOVERY_ACTION.ROLLBACK,
  REPAIR: PUBLIC_RECOVERY_ACTION.REPAIR,
  REPAIR_AUTHORITY: PUBLIC_RECOVERY_ACTION.REPAIR_AUTHORITY,
  EXPORT_REDACTED_DIAGNOSTICS: PUBLIC_RECOVERY_ACTION.EXPORT_REDACTED_DIAGNOSTICS,
} as const satisfies Readonly<Record<string, RecoveryAction>>);
export type CapabilityOperationRecoveryActionV1 = ValueOf<
  typeof CAPABILITY_OPERATION_RECOVERY_ACTION
>;
export const CAPABILITY_OPERATION_RECOVERY_ACTIONS = Object.freeze(
  Object.values(CAPABILITY_OPERATION_RECOVERY_ACTION),
);
export const isCapabilityOperationRecoveryAction = (
  value: unknown,
): value is CapabilityOperationRecoveryActionV1 =>
  memberOf(CAPABILITY_OPERATION_RECOVERY_ACTIONS, value);

const NO_CAPABILITY_OPERATION_RECOVERY_ACTIONS = frozenValues();
export const CAPABILITY_OPERATION_DEFAULT_RECOVERY_ACTIONS_BY_STATUS = Object.freeze({
  [CAPABILITY_OPERATION_STATUS.COMMITTING]: NO_CAPABILITY_OPERATION_RECOVERY_ACTIONS,
  [CAPABILITY_OPERATION_STATUS.SUCCEEDED]: NO_CAPABILITY_OPERATION_RECOVERY_ACTIONS,
  [CAPABILITY_OPERATION_STATUS.DEGRADED]: NO_CAPABILITY_OPERATION_RECOVERY_ACTIONS,
  [CAPABILITY_OPERATION_STATUS.FAILED]: frozenValues(
    CAPABILITY_OPERATION_RECOVERY_ACTION.RETRY,
    CAPABILITY_OPERATION_RECOVERY_ACTION.ROLLBACK,
  ),
  [CAPABILITY_OPERATION_STATUS.NEEDS_RECOVERY]: frozenValues(
    CAPABILITY_OPERATION_RECOVERY_ACTION.REPAIR,
    CAPABILITY_OPERATION_RECOVERY_ACTION.EXPORT_REDACTED_DIAGNOSTICS,
  ),
} satisfies Readonly<
  Record<CapabilityOperationStatusV1, readonly CapabilityOperationRecoveryActionV1[]>
>);

export const CAPABILITY_OPERATION_RECOVERY_PHASE = Object.freeze({
  FORWARD: "forward",
  ROLLBACK: CAPABILITY_OPERATION_RECOVERY_ACTION.ROLLBACK,
} as const);
export type CapabilityOperationRecoveryPhaseV1 = ValueOf<
  typeof CAPABILITY_OPERATION_RECOVERY_PHASE
>;

export const CAPABILITY_OPERATION_CHANGED_TARGET_OUTCOMES = frozenValues(
  PUBLIC_TARGET_RESULT_OUTCOME.APPLIED,
  PUBLIC_TARGET_RESULT_OUTCOME.DEGRADED,
  PUBLIC_TARGET_RESULT_OUTCOME.NEEDS_RECOVERY,
);
export const isCapabilityOperationChangedTargetOutcome = (
  value: unknown,
): value is (typeof CAPABILITY_OPERATION_CHANGED_TARGET_OUTCOMES)[number] =>
  memberOf(CAPABILITY_OPERATION_CHANGED_TARGET_OUTCOMES, value);
